name: Build & Deploy Packer Template

on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main
  # pull_request:

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-south-1
          role-session-name: GitHub-OIDC-TERRAFORM


      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.2.5

      - name: Run Packer Container - Build & Deploy
      # pull official hashicorp packer container for docker hub
        uses: docker://hashicorp/packer:light
        env: # Grab the AWS environment variables for deployment
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_GITHUB_TOKEN: ${{ secrets.AWS_GITHUB_TOKEN }}
        with:
          args: "build /github/workspace/templates/aws_template-intermediate.json"
